#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.34003
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("NumericPuzzle.Resource", IsApplication=true)]

namespace NumericPuzzle
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int blank = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int claudia = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int monoandroidsplash = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int num1 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int num10 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int num11 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int num12 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int num13 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int num14 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int num15 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int num2 = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int num3 = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int num4 = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int num5 = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int num6 = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int num7 = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int num8 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int num9 = 2130837522;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060015
			public const int chronometer = 2131099669;
			
			// aapt resource value: 0x7f060000
			public const int imageView1 = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int image_button1 = 2131099650;
			
			// aapt resource value: 0x7f06000d
			public const int image_button10 = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int image_button11 = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int image_button12 = 2131099663;
			
			// aapt resource value: 0x7f060011
			public const int image_button13 = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int image_button14 = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int image_button15 = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int image_button16 = 2131099668;
			
			// aapt resource value: 0x7f060003
			public const int image_button2 = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int image_button3 = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int image_button4 = 2131099653;
			
			// aapt resource value: 0x7f060007
			public const int image_button5 = 2131099655;
			
			// aapt resource value: 0x7f060008
			public const int image_button6 = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int image_button7 = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int image_button8 = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int image_button9 = 2131099660;
			
			// aapt resource value: 0x7f060016
			public const int start_button = 2131099670;
			
			// aapt resource value: 0x7f060001
			public const int tableRow1 = 2131099649;
			
			// aapt resource value: 0x7f060006
			public const int tableRow2 = 2131099654;
			
			// aapt resource value: 0x7f06000b
			public const int tableRow3 = 2131099659;
			
			// aapt resource value: 0x7f060010
			public const int tableRow4 = 2131099664;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int chronometer_format = 2130968578;
			
			// aapt resource value: 0x7f040004
			public const int complete_button = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int complete_title = 2130968581;
			
			// aapt resource value: 0x7f040003
			public const int start = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int time = 2130968577;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
